version: '3'
services:
  abstract:
#    build: ./abstract
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/abstract:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20002:20002"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  body:
#    build: ./body
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/body:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20001:20001"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  college:
#    build: ./college
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/college:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20003:20003"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  declaration-page:
#    build: ./declaration-page
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/declaration_page:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20004:20004"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  formula:
#    build: ./formula
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/formula:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20017:20017"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  grade:
#    build: ./grade
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/grade:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20005:20005"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  img:
#    build: ./img
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/img:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20006:20006"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  keywords:
#    build: ./keywords
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/keywords:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20007:20007"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  list:
#    build: ./list
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/list:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20008:20008"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  major:
#    build: ./major
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/major:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20009:20009"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  paper:
#    build: ./paper
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/paper:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20016:20016"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  stu_name:
#    build: ./stu_name
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/stu_name:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20010:20010"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  stu_number:
#    build: ./stu_number
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/stu_number:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20011:20011"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  table:
#    build: ./table
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/table:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20018:20018"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  tak-page:
#    build: ./tak-page
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/tak_page:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20015:20015"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  teacher_name:
#    build: ./teacher_name
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/teacher_name:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20012:20012"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  teacher_post:
#    build: ./teacher_post
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/teacher_post:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20013:20013"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  title:
#    build: ./title
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/title:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20000:20000"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure
  topic:
#    build: ./topic
    image: registry.cn-shanghai.aliyuncs.com/cmgzs/topic:${TAG}
    command: ["java", "-Xmx256m", "-Xms128m", "-XX:MaxMetaspaceSize=80m","-jar", "myapp.jar"]
    restart: always
    ports: # 指定端口映射
      - "20014:20014"
    deploy:
      resources:
        limits:
          memory: 400M
      replicas: 1
      restart_policy:
        condition: on-failure