version: '3'
services:
  rabbit:
    build: ./rabbitmq
    image: rabbitmq:3.8-management
    hostname: rabbit
    container_name: "wycs_rabbitmq3.8"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123123
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS="-rabbitmq_management listener [{port, 15672}, {ip, \"0.0.0.0\"}]"
    volumes:
      - ./data:/var/lib/rabbitmq