version: '3'
services:
  rabbit:
    build: ./rabbitmq
    image: rabbitmq:3.8-management
    hostname: rabbit
    container_name: "wycs_rabbitmq3.8"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=123123
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    volumes:
      - ./data:/var/lib/rabbitmq
  task:
    build: ./Tasks
    image: tasks:1.0
    restart: always
    ports: # 指定端口映射
      - "8080:8080"
    environment:
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    deploy:
      resources:
        limits:
          memory: 1024M
      replicas: 1
      restart_policy:
        condition: on-failure