version: '3'

services:
  rabbit:
    image: rabbitmq:3.8-management
    hostname: rabbit
    build:
      context: ./rabbitmq
    container_name: "rabbitmq3.8"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=huangzhenyu
      - RABBITMQ_DEFAULT_PASS=huangzhenyu
    volumes:
      - ./data:/var/lib/rabbitmq