version: '3'

services:
  rabbit:
    build:
      context: ./rabbitmq
    hostname: rabbit
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - ./data:/var/lib/rabbitmq

#version: '3'
#services:
#  rabbit:
#    image: rabbitmq:3.8-management
#    hostname: rabbit
#    container_name: "wycs_rabbitmq3.8"
#    restart: always
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      - RABBITMQ_DEFAULT_USER=root
#      - RABBITMQ_DEFAULT_PASS=123123
#    volumes:
#      - ./data:/var/lib/rabbitmq