version: '3'

services:
  rabbit:
    image: rabbitmq:3.8-management
    hostname: rabbit
    build:
      context: ./rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      TZ: Asia/Shanghai
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: 123456
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./conf:/etc/rabbitmq