version: '3'
services:
  rabbit:
    build: ./rabbitmq
    image: rabbitmq:3.8-management
    hostname: rabbit
    container_name: "wycs_rabbitmq3.8"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./data:/var/lib/rabbitmq